name: huaweicloud_iot_device_sdk
description: A sample command-line application.
version: 0.0.1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  crypto: ^3.0.0
  mqtt_client: ^9.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
